spring:
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    show-sql: true
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:msa-user-test
    username: sa
    password: 1234
  h2:
    console:
      enabled: true
      path: /h2-console

server:
  port: 8080